
r.define([],

	function () {

	    return { 
			Changeset_Create: 
				'<osm>' +
				'<changeset>' +
				'<tag k="created_by" v="CODAP"/>' +
				'<tag k="comment" v=">This changeset was generated by the Crowdsourced Open Data Acquisition Platform (CODAP), an experimental application developed by the Centre for Special Business Projects (CSBP-CPSE). More info on the github page (https://github.com/CSBP-CPSE/CODAP) "/>' +
				'</changeset>' +
				'</osm>'

		}
	});